apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-coordinator
  namespace: default
  labels:
    app: fleet-coordinator
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["allocation.agones.dev"]
    resources: ["gameserverallocations"]
    verbs: ["create"]
  - apiGroups: ["agones.dev"]
    resources: ["fleets"]
    verbs: ["get"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-coordinator
  namespace: default
  labels:
    app: fleet-coordinator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-coordinator
  namespace: default
  labels:
    app: fleet-coordinator
subjects:
  - kind: ServiceAccount
    name: fleet-coordinator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-coordinator
